### ISSUE TITLE
H2 In-Memory 모드로 변경

### ISSUE THREAD

**Issue by wooni97** [f-lab-edu/study-together#27]
현재 TCP 모드 사용하는 H2 Database를 Local(In-Memory) 모드로 변경

**Comment by f-lab-inno** [comment]
반대로 TCP 모드로 사용하려면 매번 H2 DB를 직접 실행해주지 않고, 어떻게 설정할 수 있을까요?

다음 블로그 글을 보고 설정해보세요
https://jehuipark.github.io/java/springboot-h2-tcp-setup
