### ISSUE TITLE
Room 생성 API

### ISSUE THREAD

**Issue by f-lab-inno** [f-lab-edu/study-together#4]
사용자가 Room을 생성할 때 사용하게 될 API를 설계하고 구현해주세요.

- 요청과 응답 디자인을 충분히 고려

**요청 e.g.)**
POST /api/v1/rooms
```
{
 ...
}
```
        
**응답 e.g.)** 
201 Created
```
{
 "roomId": 1
}
```

**Comment by wooni97** [comment]
요청
POST /api/v1/rooms
{
	“roomName” : “공부방”,
	“total” : 10,
	“createDate”: “20230907",
	“managerSeqID”: 2
}
응답
{
	“roomID”: 1
}

**Comment by f-lab-inno** [comment]
> 요청 POST /api/v1/rooms { “roomName” : “공부방”, “total” : 10, “createDate”: “20230907", “managerSeqID”: 2 } 응답 { “roomID”: 1 }

구현시 PR 링크 걸어주세요~
