### ISSUE TITLE
Scheduler 생성 API

### ISSUE THREAD

**Issue by f-lab-inno** [f-lab-edu/study-together#5]
사용자가 Scheduler을 생성할 때 사용하게 될 API를 설계하고 구현해주세요.

- scheduler 생성시 해당 스케줄러의 todo까지 같이 요청 받을것인지? API를 분리할것인지 고려
- 요청과 응답 디자인을 충분히 고려

**요청 e.g.)**
POST /api/v1/schedulers
```
{
 ...
}
```
        
**응답 e.g.)** 
201 Created
```
{
 "schedulerId": 1,
 "todos": [1, 2, 3]
}
```

**Comment by wooni97** [comment]
요청
POST /api/v1/schedulers
{
	“date” : “20230907”,
	“seq_id” : 2,
	“id” : “testID123”
	“todos” : [“책읽기”, “예습”,...]
}
응답
{
	“scheduler_seq” : 3
}

특정 날짜에 스케줄러 생성 -> todo 생성이 무조건적으로 연결되게 구현할 예정이라
todos 안에 배열로 넣는식으로 설계해봤습니다.
서버에서 배열 안에 데이터를 순차적으로 돌면서 todo에 1,2,3..으로 sequence를 부여해주면 되지 않을까요?

**Comment by f-lab-inno** [comment]
> 요청 POST /api/v1/schedulers { “date” : “20230907”, “seq_id” : 2, “id” : “testID123” “todos” : [“책읽기”, “예습”,...] } 응답 { “scheduler_seq” : 3 }
> 
> 특정 날짜에 스케줄러 생성 -> todo 생성이 무조건적으로 연결되게 구현할 예정이라 todos 안에 배열로 넣는식으로 설계해봤습니다. 서버에서 배열 안에 데이터를 순차적으로 돌면서 todo에 1,2,3..으로 sequence를 부여해주면 되지 않을까요?

그것도 괜찮을 것 같네요! 구현해서 PR 링크 여기에다 걸어주세요~
